package pcl.bridgebot.chatserverlink;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import static org.junit.Assert.*;

public class ChatServerLinkTest {
    @Test
    public void itSHouldInitializeTheChatServerLinkProperly() {
        new ChatServerLink("", 0);
        assertTrue(true);
    }
}